<?php

namespace KRG\FileBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('upload', FileUploadType::class)
                ->add('files', HiddenType::class);
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'multiple' => false,
            'mime_types' => array(),
            'max_upload_size' => 0,
            'limit' => 0,
            'adapters' => array('local')
        ));
        $resolver->setAllowedTypes(array(
            'multiple' => 'bool',
            'mime_types' => 'array',
            'max_upload_size' => 'int',
            'limit' => 'int',
            'adapters' => 'array'
        ));
    }


}